# Generated by Django 2.2.3 on 2019-07-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Activity')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Task')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Provider')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ServiceType')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='Provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Provider'),
        ),
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Action'),
        ),
        migrations.AddField(
            model_name='activity',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ServiceType'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ActionClass'),
        ),
    ]
