# Generated by Django 2.2.3 on 2019-07-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Provider',
            new_name='provider',
        ),
        migrations.AddField(
            model_name='task',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Action'),
        ),
        migrations.AddField(
            model_name='task',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Provider'),
        ),
        migrations.AddField(
            model_name='task',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.ServiceType'),
        ),
    ]
