# Generated by Django 2.2.3 on 2019-07-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190714_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='service_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='provider_service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.ProviderServiceType'),
            preserve_default=False,
        ),
    ]
