# Generated by Django 2.2.3 on 2019-07-14 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190714_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='provider_service_type',
        ),
        migrations.AddField(
            model_name='task',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Provider'),
        ),
        migrations.AddField(
            model_name='task',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.ServiceType'),
        ),
    ]
