# Generated by Django 2.2.3 on 2019-07-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20190716_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admintask',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ProviderTaskOption',
        ),
    ]
