# Generated by Django 2.2.3 on 2019-07-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20190716_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTaskOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('provider_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ProviderTask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Task')),
            ],
        ),
    ]
