# Generated by Django 2.2.3 on 2019-07-16 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_providertaskoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTaskChoice',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workflow.Task')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ProviderTask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ProviderTaskChoice')),
            ],
        ),
        migrations.DeleteModel(
            name='ProviderTaskOption',
        ),
    ]
