# Generated by Django 2.2.3 on 2019-07-16 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20190716_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderChoiceTask',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workflow.Task')),
                ('name', models.CharField(max_length=50)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Action')),
            ],
        ),
        migrations.RemoveField(
            model_name='providertaskgroup',
            name='provider_task',
        ),
        migrations.RemoveField(
            model_name='providertaskgroup',
            name='task',
        ),
        migrations.DeleteModel(
            name='ProviderTaskChoice',
        ),
        migrations.DeleteModel(
            name='ProviderTaskGroup',
        ),
    ]
