# Generated by Django 2.2.3 on 2019-07-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20190716_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerchoicetask',
            old_name='name',
            new_name='heading',
        ),
    ]
