# Generated by Django 2.2.3 on 2019-07-16 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20190716_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='providerchoicetask',
            name='action',
        ),
        migrations.RemoveField(
            model_name='providerchoicetask',
            name='heading',
        ),
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Action'),
            preserve_default=False,
        ),
    ]
