# Generated by Django 2.2.3 on 2019-07-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20190716_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerchoicetask',
            name='heading',
            field=models.CharField(default='heading', max_length=50),
            preserve_default=False,
        ),
    ]
