# Generated by Django 2.2.3 on 2019-07-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_remove_providerchoicetask_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerchoicetask',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Action'),
            preserve_default=False,
        ),
    ]
